language: node_js

env:
  global:
  # Cannot test actual download content from CI servers, HTML response.
  - SKIP_TEST_DL=1
  - FORCE_REQUEST_DL=1

matrix:
  include:
  - node_js: v10.0.0
    env:
    - NO_LINT=1
  - node_js: v14.8.0

script:
- npm run clean
- if [ "$NO_LINT" != "1" ]; then npm run lint; fi
- npm run build
- travis_retry npm run test
