name: main

on:
  push:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        config:
          - node-version: '10.13.0'
            NO_LINT: 1
          - node-version: '12.13.0' # LTS
            NO_LINT: 1
          - node-version: '14.15.0' # LTS
            NO_LINT: 1
          - node-version: '16.9.0'

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.config.node-version }}

    - run: npm install
    - run: npm run clean
    - run: npm run lint
      if: matrix.config.NO_LINT != 1
    - run: npm run build
    - run: npm run test
      env:
        # Cannot test actual download content from CI servers, HTML response.
        SKIP_TEST_DL: 1
        FORCE_REQUEST_DL: 1
